import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { loadMobileAppData, saveMobileAppData, createRecord, deleteRecord, generateAIInsight } from './lib/mobileStorage';
import { useMemo, useState } from 'react';
import { Home, Users, CalendarDays, Bot, Grid3X3, Bell } from 'lucide-react';
const Shell = ({ children }) => _jsx("div", { className: 'min-h-screen bg-gradient-to-b from-slate-100 to-cyan-50 py-4', children: _jsxs("div", { className: 'mx-auto max-w-[430px] min-h-screen bg-white shadow-2xl rounded-3xl overflow-hidden relative', children: [_jsx("div", { className: 'p-4 pb-28', children: children }), _jsx(BottomNav, {})] }) });
const BottomNav = () => { const items = [['/app', 'Home', Home], ['/app/patients', 'Pasien', Users], ['/app/schedule', 'Jadwal', CalendarDays], ['/app/ai', 'AI', Bot], ['/app/more', 'Lainnya', Grid3X3]]; return _jsx("nav", { className: 'fixed bottom-0 left-1/2 -translate-x-1/2 w-full max-w-[430px] bg-white/90 backdrop-blur border-t rounded-t-2xl', children: _jsx("div", { className: 'grid grid-cols-5', children: items.map(([to, label, Icon]) => _jsxs(NavLink, { to: to, className: ({ isActive }) => `min-h-11 py-2 flex flex-col items-center text-xs ${isActive ? 'text-cyan-700' : 'text-slate-500'}`, children: [_jsx(Icon, { size: 18 }), label] }, to)) }) }); };
const Login = () => { const navigate = useNavigate(); const roles = ['Pasien', 'Dokter Spesialis', 'Fisikawan Medis', 'Admin Rumah Sakit', 'Manajemen', 'Caregiver / Pendamping']; return _jsx("div", { className: 'min-h-screen grid place-items-center p-4 bg-slate-100', children: _jsxs("div", { className: 'w-full max-w-[430px] bg-white rounded-3xl p-5 shadow', children: [_jsx("h1", { className: 'text-2xl font-bold', children: "RADCARE NUSANTARA" }), _jsx("p", { className: 'text-sm text-slate-600 mb-4', children: "Pilih Mode Aplikasi" }), _jsx("div", { className: 'grid gap-3', children: roles.map(r => _jsx("button", { onClick: () => { const d = loadMobileAppData(); d.selectedRole = r; saveMobileAppData(d); alert(`Login sukses sebagai ${r}`); navigate('/app'); }, className: 'p-3 rounded-2xl border text-left hover:border-cyan-500', children: r }, r)) })] }) }); };
const HomePage = () => { const d = loadMobileAppData(); return _jsxs(Shell, { children: [_jsxs("div", { className: 'flex justify-between items-start', children: [_jsxs("div", { children: [_jsxs("p", { className: 'font-semibold', children: ["Halo, ", d.selectedRole] }), _jsx("p", { className: 'text-xs text-slate-500', children: new Date().toLocaleDateString('id-ID') })] }), _jsx(Bell, { size: 18 })] }), _jsxs("div", { className: 'mt-4 rounded-3xl bg-gradient-to-r from-slate-900 to-cyan-700 text-white p-4', children: [_jsx("p", { className: 'font-semibold', children: "Smart Radiotherapy Care" }), _jsx("p", { className: 'text-xs opacity-90', children: "Continuous Specialist Monitoring" })] }), _jsx("div", { className: 'grid grid-cols-2 gap-3 mt-4', children: [['Pasien Aktif', d.patients.length], ['Jadwal Hari Ini', d.schedules.length], ['Risiko Tinggi', d.patients.filter(p => p.riskLevel === 'Tinggi').length], ['Sesi Selesai', d.treatmentPlans.reduce((a, b) => a + b.completedSessions, 0)]].map(([t, v]) => _jsxs("div", { className: 'rounded-2xl bg-slate-50 p-3', children: [_jsx("p", { className: 'text-xs', children: t }), _jsx("p", { className: 'text-xl font-bold', children: String(v) })] }, String(t))) })] }); };
const Patients = () => { const [q, setQ] = useState(''); const [d, setD] = useState(loadMobileAppData()); const data = useMemo(() => d.patients.filter(p => p.name.toLowerCase().includes(q.toLowerCase())), [q, d]); return _jsxs(Shell, { children: [_jsxs("div", { className: 'flex gap-2', children: [_jsx("input", { className: 'border rounded-xl p-2 w-full', placeholder: 'Search pasien', value: q, onChange: e => setQ(e.target.value) }), _jsx(NavLink, { to: '/app/patients/new', className: 'bg-cyan-700 text-white px-3 rounded-xl grid place-items-center', children: "+" })] }), _jsx("div", { className: 'mt-3 space-y-2', children: data.map(p => _jsxs("div", { className: 'border rounded-2xl p-3', children: [_jsx("p", { className: 'font-semibold', children: p.name }), _jsxs("p", { className: 'text-xs', children: [p.patientId, " \u2022 ", p.diagnosis] }), _jsxs("div", { className: 'flex gap-2 mt-2', children: [_jsx(NavLink, { to: `/app/patients/${p.id}`, className: 'text-cyan-700 text-sm', children: "Detail" }), _jsx("button", { onClick: () => { setD(deleteRecord('patients', p.id)); }, className: 'text-rose-600 text-sm', children: "Hapus" })] })] }, p.id)) })] }); };
const PatientNew = () => { const nav = useNavigate(); const [name, setName] = useState(''); return _jsxs(Shell, { children: [_jsx("input", { className: 'border rounded-xl p-2 w-full', placeholder: 'Nama pasien', value: name, onChange: e => setName(e.target.value) }), _jsx("button", { className: 'mt-3 bg-cyan-700 text-white w-full rounded-xl p-3', onClick: () => { createRecord('patients', { name, patientId: 'RCN-NEW', age: 45, gender: 'Laki-laki', diagnosis: 'Dummy', cancerType: 'Dummy', stage: 'II', doctor: 'dr.', physicist: 'fis.', totalSessions: 20, completedSessions: 0, status: 'Aktif', riskLevel: 'Sedang', startDate: '2026-05-25', notes: '' }); nav('/app/patients'); }, children: "Simpan" })] }); };
const AIPage = () => { const [prompt, setPrompt] = useState('Pasien mana yang perlu evaluasi?'); const [d, setD] = useState(loadMobileAppData()); return _jsxs(Shell, { children: [_jsx("div", { className: 'rounded-3xl p-4 text-white bg-gradient-to-br from-slate-900 to-blue-700', children: "AI Assistant RADCARE" }), _jsx("p", { className: 'text-xs mt-2', children: "AI Assistant hanya simulasi berbasis data dummy dan tidak menggantikan keputusan klinis tenaga kesehatan." }), _jsx("textarea", { className: 'border rounded-xl p-2 w-full mt-3', value: prompt, onChange: e => setPrompt(e.target.value) }), _jsx("button", { className: 'bg-cyan-700 text-white w-full rounded-xl p-3 mt-2', onClick: () => { generateAIInsight(prompt); setD(loadMobileAppData()); }, children: "Generate Insight" }), _jsx("div", { className: 'mt-3 space-y-2', children: d.aiInsights.slice(0, 6).map(i => _jsx("div", { className: 'bg-slate-50 rounded-2xl p-3 text-sm', children: i.result }, i.id)) })] }); };
const Simple = (title) => _jsxs(Shell, { children: [_jsx("h2", { className: 'font-semibold text-lg', children: title }), _jsx("p", { className: 'text-sm text-slate-500', children: "Fitur mobile RADCARE tersedia dengan data localStorage." })] });
export default function App() {
    return _jsxs(Routes, { children: [_jsx(Route, { path: '/', element: _jsx(Navigate, { to: '/login' }) }), _jsx(Route, { path: '/login', element: _jsx(Login, {}) }), _jsx(Route, { path: '/app', element: _jsx(HomePage, {}) }), _jsx(Route, { path: '/app/patients', element: _jsx(Patients, {}) }), _jsx(Route, { path: '/app/patients/new', element: _jsx(PatientNew, {}) }), _jsx(Route, { path: '/app/patients/:id', element: Simple('Detail Pasien') }), _jsx(Route, { path: '/app/schedule', element: Simple('Jadwal Terapi') }), _jsx(Route, { path: '/app/monitoring', element: Simple('Monitoring Gejala') }), _jsx(Route, { path: '/app/treatment', element: Simple('Rencana Terapi') }), _jsx(Route, { path: '/app/notes', element: Simple('Catatan Klinis') }), _jsx(Route, { path: '/app/ai', element: _jsx(AIPage, {}) }), _jsx(Route, { path: '/app/reports', element: Simple('Laporan') }), _jsx(Route, { path: '/app/documents', element: Simple('Dokumen') }), _jsx(Route, { path: '/app/education', element: Simple('Edukasi') }), _jsx(Route, { path: '/app/notifications', element: Simple('Notifikasi') }), _jsx(Route, { path: '/app/profile', element: Simple('Profil') }), _jsx(Route, { path: '/app/settings', element: Simple('Pengaturan') }), _jsx(Route, { path: '/app/more', element: Simple('Menu Lainnya') }), _jsx(Route, { path: '/app/journey', element: Simple('Radiotherapy Journey Map') }), _jsx(Route, { path: '/app/risk-heatmap', element: Simple('Smart Risk Heatmap') }), _jsx(Route, { path: '/app/priority', element: Simple('Clinical Priority Queue') }), _jsx(Route, { path: '/app/symptom-diary', element: Simple('Patient Symptom Diary') }), _jsx(Route, { path: '/app/follow-up', element: Simple('Smart Follow-Up Reminder') }), _jsx(Route, { path: '/app/continuity-score', element: Simple('Care Continuity Score') })] });
}
